environments:
  dev:
  preprod:
  prod:

templates:
  default:
    chart: yesodot/common
    namespace: {{ requiredEnv "NAMESPACE" | quote }}
    version: {{ requiredEnv "COMMON_VERSION" | default "3.0.0"}}
    values:
      - ../shared/shared.yaml
      - ../shared/{{`{{ .Release.Name }}`}}.yaml
      - ../{{`{{ .Environment.Name }}`}}/shared.yaml
      - ../{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}.yaml
    installed: true

repositories:
- name: yesodot
  url: https://harborreg-2.northeurope.cloudapp.azure.com/chartrepo/kraise
  username: {{ requiredEnv "HARBOR_USER" }}
  password: {{ requiredEnv "HARBOR_PASSWORD" }}

{{ $folderPath := printf "./%s/" .Environment.Name }}
releases:
{{ range $index, $item := readDirEntries $folderPath }}
  {{ $isShared := contains "shared" $item.Name }}
  {{- if not $isShared }}
  - name: {{ $item.Name | replace ".yaml" "" | quote }}
    inherit:
    - template: default
  {{ end }}
{{- end }}

helmDefaults:
  createNamespace: false